layout_spectrum: 0.07475591927591602
typography_spectrum: 0.592017519911659
color:
  saturation: 0.07139240252711618
  brandStrength: 0.10606668903953442
  lightness: 0.5271651375492906
  rhythmicContrast: 0.33324440992317433
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
content_rating:
  adult: false
opengraph:
  type: FUSIONproto
  appId: 'https://www.facebook.com/FUSIONproto/'
analytics:
  google: UA-103167574-2
  facebook: '395447697488990'
author:
  name: HOME
  email: info@fusionpm.com
  url: 'http://www.fusionpm.us'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c4b0533-1bec-4110-8fa6-058683490ff8.tif
name: www.fusionpm.us
url: 'https://fusionpm.us/'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab3ba7c5-bcc1-46eb-9bb6-6476d48b0546.png
title: FUSION
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac042cbe-168b-4fd6-9425-2dbc194e0ec7.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac042cbe-168b-4fd6-9425-2dbc194e0ec7.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Prototype Manufacturing
purpose:
  - type: contact
    url: 'tel:6198195521'
    label: CALL
github: true
