typography_spectrum: 0.6616635251784753
content_rating:
  adult: false
color:
  saturation: 0.11429734161197401
  brandStrength: 0.4294694366222155
  lightness: 0.13540931062256495
  rhythmicContrast: 0.5801715976159355
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
github: true
opengraph:
  type: FUSIONproto
  appId: 'https://www.facebook.com/FUSIONproto/'
layout_spectrum: 0.781928340595234
analytics:
  google: UA-103167574-2
  facebook: '395447697488990'
author:
  name: FUSION PROTOTYPES
  email: info@fusionpm.com
  url: 'http://www.fusionpm.us'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c4b0533-1bec-4110-8fa6-058683490ff8.tif
name: www.fusionpm.us
url: 'https://fusionpm.us/'
navigation:
  - name: FACEBOOK
    url: 'https://www.facebook.com/FUSIONproto/'
    type: external
  - name: INSTAGRAM
    url: 'https://www.instagram.com/fusion_proto/?hl=es-la'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab3ba7c5-bcc1-46eb-9bb6-6476d48b0546.png
title: FUSION
content: []
description: Prototype Manufacturing
purpose:
  - type: contact
    url: 'tel:6198195521'
    label: CALL
