layout_spectrum: 0.13073017273328758
typography_spectrum: 0.6595564173603671
color:
  saturation: 0.9980832772851359
  brandStrength: 0.37730102228941303
  lightness: 0.32880112864842437
  rhythmicContrast: 0.21871479446713876
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
content_rating:
  adult: false
github: true
opengraph:
  type: FUSIONproto
  appId: 'https://www.facebook.com/FUSIONproto/'
analytics:
  google: UA-103167574-1
  facebook: '395447697488990'
author:
  name: FUSION PROTOTYPES
  email: info@fusionpm.com
  url: 'http://www.fusionpm.us.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c4b0533-1bec-4110-8fa6-058683490ff8.tif
name: www.fusionpm.us.com
navigation:
  - name: PORTFOLIO
    id: fdfcccea-f33a-48fe-b0fd-3a68986a4258
    type: content
  - name: PROTOTYPES
    id: 0997b923-0e62-4840-9663-5a5a1bfb5f25
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab3ba7c5-bcc1-46eb-9bb6-6476d48b0546.png
title: FUSION
content: []
description: Prototype Manufacturing
purpose:
  - type: contact
    url: 'tel:6198195521'
    label: CALL US
  - type: email
    url: 'mailto:info@fusionpm.com'
    label: SEND EMAIL
