layout_spectrum: 0.1552346180280726
typography_spectrum: 0.2535141598811318
color:
  saturation: 0.5108943776996566
  brandStrength: 0.38470904706479375
  lightness: 0.05867663858928672
  rhythmicContrast: 0.5476602990185787
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
content_rating:
  adult: false
github: true
opengraph:
  type: FUSIONproto
  appId: 'https://www.facebook.com/FUSIONproto/'
analytics:
  google: UA-103167574-2
  facebook: '395447697488990'
author:
  name: FUSION PROTOTYPES
  email: info@fusionpm.com
  url: 'http://www.fusionpm.us'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c4b0533-1bec-4110-8fa6-058683490ff8.tif
name: www.fusionpm.us
url: 'https://fusionpm.us/'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab3ba7c5-bcc1-46eb-9bb6-6476d48b0546.png
title: FUSION
content: []
description: Prototype Manufacturing
purpose:
  - type: contact
    url: 'tel:6198195521'
    label: CALL
  - type: email
    url: 'mailto:info@fusionpm.com'
    label: SEND EMAIL
