typography_spectrum: 0.7045657805443769
content_rating:
  adult: false
color:
  saturation: 0.5122060132036815
  brandStrength: 0.9469475543136606
  lightness: 0.417362462870666
  rhythmicContrast: 0.028597380251134976
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
github: true
opengraph:
  type: FUSIONproto
  appId: 'https://www.facebook.com/FUSIONproto/'
layout_spectrum: 0.6182917190202982
analytics:
  google: UA-103167574-1
  facebook: '395447697488990'
author:
  name: FUSION PROTOTYPES
  email: info@fusionpm.com
  url: 'http://www.fusionpm.us'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c4b0533-1bec-4110-8fa6-058683490ff8.tif
name: www.fusionpm.us
url: 'https://fusionpm.us/'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab3ba7c5-bcc1-46eb-9bb6-6476d48b0546.png
title: FUSION
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FLB4-0LKjN8Q%3Fstart%3D11%26feature%3Doembed%26start%3D11&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DLB4-0LKjN8Q&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FLB4-0LKjN8Q%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=LB4-0LKjN8Q&t=11s'
      keywords:
        - ''
      related: []
      author:
        - name: FUSIONpm
          url: 'https://www.youtube.com/channel/UCRrzItIqRKeE2MpBmrb0gyQ'
          avatar: {}
      '@context': 'http://schema.org'
      title: FUSION's Philosophy
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=LB4-0LKjN8Q&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=LB4-0LKjN8Q&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=LB4-0LKjN8Q&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=LB4-0LKjN8Q&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=LB4-0LKjN8Q&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=LB4-0LKjN8Q'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=LB4-0LKjN8Q
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=LB4-0LKjN8Q
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      description: Uploaded by FUSIONpm on 2017-05-25.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Prototype Manufacturing
purpose:
  - type: contact
    url: 'tel:6198195521'
    label: CALL
  - type: email
    url: 'mailto:info@fusionpm.com'
    label: SEND EMAIL
